version: '2.1'

services:
  app1:
    build:
      context: app
    image: nginx-tutorial-app
    entrypoint: ["gunicorn", "-w 4", "-b 0.0.0.0:8000", "mock:app"]
    ports:
      - 8000:8000
  app2:
    build:
      context: app
    image: nginx-tutorial-app
    entrypoint: ["gunicorn", "-w 4", "-b 0.0.0.0:8001", "mock:app"]
    ports:
      - 8001:8001
  nginx:
    build:
      context: nginx
    image: nginx-tutorial-nginx
    ports:
      - 80:80
      - 88:88
      - 888:888
      - 8888:8888
